import type { Filters, PromoDto, PromoPartnerDto, PromoStatus } from "../../types";
const statusOrder: Record<PromoStatus, number> = { active: 0, planned: 1, finished: 2 };
export function getPartnerColumns(promos: PromoDto[]): string[] { return [...new Set(promos.flatMap((promo) => promo.partners.map((partner) => partner.partnerName)))].sort((a, b) => a.localeCompare(b)); }
export function getVisiblePartnerColumns(available: string[], selected: string[] | null): string[] { return selected === null ? available : available.filter((partner) => selected.includes(partner)); }
export function filterPromos(promos: PromoDto[], filters: Filters): PromoDto[] { const query = filters.search.trim().toLocaleLowerCase(); return promos.filter((promo) => { const search = !query || [promo.name, promo.lob, ...promo.partners.map((partner) => partner.partnerName)].some((value) => value.toLocaleLowerCase().includes(query)); return search && (!filters.lob || promo.lob === filters.lob) && (!filters.status || promo.status === filters.status) && (!filters.partner || promo.partners.some((partner) => partner.partnerName === filters.partner)); }); }
export function countPendingReports(promos: PromoDto[], partnerName = ""): number { return promos.reduce((count, promo) => count + (promo.status === "finished" ? promo.partners.filter((partner) => !partner.reportReceived && (!partnerName || partner.partnerName === partnerName)).length : 0), 0); }
export function sortPromos(promos: PromoDto[]): PromoDto[] { return [...promos].sort((a, b) => statusOrder[a.status] - statusOrder[b.status] || Date.parse(b.startDate) - Date.parse(a.startDate)); }
export type PartnerCellState = "none" | "participating" | "pending" | "received";
export function getPartnerCellState(status: PromoStatus, partner?: PromoPartnerDto): PartnerCellState { if (!partner) return "none"; if (status !== "finished") return "participating"; return partner.reportReceived ? "received" : "pending"; }
