import { useEffect, useMemo, useState } from "react";
import { PromoDrawer } from "./components/PromoDrawer";
import { TrackerTable } from "./components/TrackerTable";
import { TrackerToolbar } from "./components/TrackerToolbar";
import { getPromo, getPromos, updateReportStatus } from "./shared/api/client";
import { filterPromos, getPartnerColumns, sortPromos } from "./shared/lib/tracker";
import type { Filters, PromoDto } from "./types";
const initialFilters: Filters = { search: "", lob: "", status: "", partner: "" };
export default function App() {
  const [promos, setPromos] = useState<PromoDto[]>([]); const [filters, setFilters] = useState(initialFilters); const [pendingOnly, setPendingOnly] = useState(false); const [selected, setSelected] = useState<PromoDto | null>(null); const [busyId, setBusyId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { getPromos().then(setPromos).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  const partners = useMemo(() => getPartnerColumns(promos), [promos]); const visiblePromos = useMemo(() => { const filtered = filterPromos(promos, filters); return sortPromos(pendingOnly ? filtered.filter((promo) => promo.status === "finished" && promo.partners.some((partner) => !partner.reportReceived)) : filtered); }, [promos, filters, pendingOnly]); const pending = promos.reduce((count, promo) => count + (promo.status === "finished" ? promo.partners.filter((partner) => !partner.reportReceived).length : 0), 0);
  const selectPromo = async (id: string) => { try { setSelected(await getPromo(id)); } catch (reason) { setError((reason as Error).message); } };
  const toggleReport = async (id: string, received: boolean) => { setBusyId(id); try { const updated = await updateReportStatus(id, received); const apply = (promo: PromoDto) => ({ ...promo, partners: promo.partners.map((partner) => partner.promoPartnerId === id ? { ...partner, reportReceived: updated.reportReceived, reportReceivedAt: updated.reportReceivedAt } : partner) }); setPromos((current) => current.map(apply)); setSelected((current) => current ? apply(current) : null); } catch (reason) { setError((reason as Error).message); } finally { setBusyId(null); } };
  const showAll = () => { setPendingOnly(false); setFilters(initialFilters); };
  return <div className="shell"><aside className="sidebar"><div className="brand"><span>PT</span>Promo Tracker</div><nav aria-label="Основна навігація"><button className={!pendingOnly ? "active" : ""} onClick={showAll}>Огляд</button><button onClick={showAll}>Усі промо</button><button className={pendingOnly ? "active" : ""} onClick={() => { setPendingOnly(true); setFilters(initialFilters); }}>Очікуються звіти <em>{pending}</em></button><button onClick={showAll}>Партнери</button></nav><p>Telegram — канал додавання промо</p></aside><main><header className="page-header"><div><span className="eyebrow">Робочий простір KAM</span><h1>Promo Tracker</h1><p>Промоактивності та звіти партнерів</p></div><div className="summary"><div><span>Активні</span><strong>{promos.filter((promo) => promo.status === "active").length}</strong></div><div><span>Заплановані</span><strong>{promos.filter((promo) => promo.status === "planned").length}</strong></div><div><span>Очікуються звіти</span><strong>{pending}</strong></div></div></header>
    {error && <div className="error" role="alert">{error}<button onClick={() => setError("")}>×</button></div>}<TrackerToolbar filters={filters} setFilters={setFilters} lobs={[...new Set(promos.map((promo) => promo.lob))].sort()} partners={partners} />{loading ? <div className="empty">Завантаження…</div> : promos.length === 0 ? <div className="empty">Промо ще не додані.</div> : <TrackerTable promos={visiblePromos} partners={partners} onSelect={selectPromo} />}</main>{selected && <PromoDrawer promo={selected} busyId={busyId} onClose={() => setSelected(null)} onToggle={toggleReport} />}</div>;
}
