import type { Partner, Promo, PromoPartner, User } from "@prisma/client";
import request from "supertest";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { createApi, type ApiDependencies } from "../src/api/createApi.js";
import { hashPassword } from "../src/features/auth/password.js";

const secret = "test-secret-that-is-at-least-32-characters"; const createdAt = new Date("2026-09-01T00:00:00Z"); let passwordHash = "";
beforeAll(async () => { passwordHash = await hashPassword("correct-password"); });
const makeUser = (role: User["role"] = "USER", active = true): User => ({ id: role === "USER" ? 1 : 2, email: `${role.toLowerCase()}@example.com`, passwordHash, role, isActive: active, createdAt, updatedAt: createdAt });
const promo: Promo = { id: "promo-1", lob: "AW", name: "Promo", normalizedName: "promo", startDate: createdAt, endDate: createdAt, createdAt, updatedAt: createdAt }; const partner: Partner = { id: "partner-1", name: "Rozetka", createdAt, updatedAt: createdAt }; const relation: PromoPartner = { id: "relation-1", promoId: promo.id, partnerId: partner.id, rawEmailSubject: "Promo", reportReceived: false, reportReceivedAt: null, firstReminderSentAt: null, secondReminderSentAt: null, createdAt, updatedAt: createdAt }; const promoRecord = { ...promo, partners: [{ ...relation, partner }] };
function deps(user: User | null, overrides: Partial<ApiDependencies> = {}): Partial<ApiDependencies> { return { jwtSecret: secret, findUserByEmail: vi.fn().mockImplementation(async (email) => user?.email === email.trim().toLowerCase() ? user : null), findUserById: vi.fn().mockImplementation(async (id) => user?.id === id ? user : null), getAllPromos: vi.fn().mockResolvedValue([promoRecord]), getPromoById: vi.fn().mockResolvedValue(promoRecord), getPendingReports: vi.fn().mockResolvedValue([]), getPromoPartnerById: vi.fn().mockResolvedValue(relation), markReportReceived: vi.fn().mockResolvedValue({ ...relation, reportReceived: true }), markReportPending: vi.fn().mockResolvedValue(relation), deletePromo: vi.fn().mockResolvedValue(true), removePromoPartner: vi.fn().mockResolvedValue(true), now: () => createdAt, ...overrides }; }
async function loginAgent(user: User) { const agent = request.agent(createApi(deps(user))); const response = await agent.post("/api/auth/login").send({ email: user.email, password: "correct-password" }); expect(response.status).toBe(200); return agent; }

describe("authentication API", () => {
  it("logs in an active user and never returns passwordHash", async () => { const user = makeUser(); const response = await request(createApi(deps(user))).post("/api/auth/login").send({ email: user.email, password: "correct-password" }); expect(response.status).toBe(200); expect(response.body).toEqual({ id: 1, email: user.email, role: "USER" }); expect(JSON.stringify(response.body)).not.toContain("passwordHash"); expect(response.headers["set-cookie"][0]).toContain("HttpOnly"); });
  it("rejects a wrong password", async () => { const user = makeUser(); expect((await request(createApi(deps(user))).post("/api/auth/login").send({ email: user.email, password: "wrong-password" })).status).toBe(401); });
  it("rejects an unknown user", async () => expect((await request(createApi(deps(null))).post("/api/auth/login").send({ email: "missing@example.com", password: "correct-password" })).status).toBe(401));
  it("rejects an inactive user login", async () => { const user = makeUser("USER", false); expect((await request(createApi(deps(user))).post("/api/auth/login").send({ email: user.email, password: "correct-password" })).status).toBe(401); });
  it("returns the authenticated user from /auth/me", async () => { const user = makeUser(); const agent = await loginAgent(user); const response = await agent.get("/api/auth/me"); expect(response.body).toEqual({ id: 1, email: user.email, role: "USER" }); });
  it("returns 401 from /auth/me without a session", async () => expect((await request(createApi(deps(makeUser()))).get("/api/auth/me")).status).toBe(401));
  it("blocks an inactive user even with an existing cookie", async () => { const user = makeUser(); const agent = await loginAgent(user); user.isActive = false; expect((await agent.get("/api/promos")).status).toBe(401); });
  it("logout clears authentication", async () => { const agent = await loginAgent(makeUser()); const logout = await agent.post("/api/auth/logout"); expect(logout.headers["set-cookie"][0]).toMatch(/Expires=Thu, 01 Jan 1970|Max-Age=0/); expect((await agent.get("/api/auth/me")).status).toBe(401); });
});

describe("API authorization", () => {
  it("rejects unauthenticated tracker access", async () => expect((await request(createApi(deps(makeUser()))).get("/api/promos")).status).toBe(401));
  it("allows USER to read tracker", async () => expect((await (await loginAgent(makeUser())).get("/api/promos")).status).toBe(200));
  it("allows USER to toggle report state", async () => expect((await (await loginAgent(makeUser())).patch("/api/promo-partners/relation-1/report").send({ received: true })).status).toBe(200));
  it("returns 403 when USER directly deletes promo", async () => expect((await (await loginAgent(makeUser())).delete("/api/promos/promo-1")).status).toBe(403));
  it("returns 403 when USER directly removes a partner", async () => expect((await (await loginAgent(makeUser())).delete("/api/promos/promo-1/partners/partner-1")).status).toBe(403));
  it("allows SUPERUSER to delete a promo", async () => { const remove = vi.fn().mockResolvedValue(true); const superuser = makeUser("SUPERUSER"); const agent = request.agent(createApi(deps(superuser, { deletePromo: remove }))); await agent.post("/api/auth/login").send({ email: superuser.email, password: "correct-password" }); expect((await agent.delete("/api/promos/promo-1")).status).toBe(200); expect(remove).toHaveBeenCalledWith("promo-1"); });
  it("allows SUPERUSER to remove a promo partner", async () => { const remove = vi.fn().mockResolvedValue(true); const superuser = makeUser("SUPERUSER"); const agent = request.agent(createApi(deps(superuser, { removePromoPartner: remove }))); await agent.post("/api/auth/login").send({ email: superuser.email, password: "correct-password" }); expect((await agent.delete("/api/promos/promo-1/partners/partner-1")).status).toBe(200); expect(remove).toHaveBeenCalledWith("promo-1", "partner-1"); });
  it("returns 404 when SUPERUSER deletes an unknown promo", async () => { const superuser = makeUser("SUPERUSER"); const agent = request.agent(createApi(deps(superuser, { deletePromo: vi.fn().mockResolvedValue(false) }))); await agent.post("/api/auth/login").send({ email: superuser.email, password: "correct-password" }); expect((await agent.delete("/api/promos/missing")).status).toBe(404); });
  it("returns 404 when SUPERUSER removes an unknown relation", async () => { const superuser = makeUser("SUPERUSER"); const agent = request.agent(createApi(deps(superuser, { removePromoPartner: vi.fn().mockResolvedValue(false) }))); await agent.post("/api/auth/login").send({ email: superuser.email, password: "correct-password" }); expect((await agent.delete("/api/promos/promo-1/partners/missing")).status).toBe(404); });
});
