import { Prisma, type User, type UserRole } from "@prisma/client";
import cookieParser from "cookie-parser";
import cors from "cors";
import express, { type NextFunction, type Request, type RequestHandler, type Response } from "express";
import path from "node:path";
import { AUTH_SESSION_MAX_AGE_MS, authenticateUser, findUserByEmail, findUserById, signAuthToken, toSafeUser } from "../features/auth/authService.js";
import { AUTH_COOKIE, requireAuth, requireCapability } from "../features/auth/authMiddleware.js";
import { createManagedUser, deleteManagedKam, LastActiveSuperuserError, listUsers, SuperuserDeletionError, updateManagedUser, updateManagedUserPassword, type ManagedUser, type UserAdminUpdate } from "../features/auth/userAdmin.js";
import { deletePromo, removePromoPartner } from "../features/promoAdmin/deletePromo.js";
import { resolvePartnerAccessScope } from "../features/partnerAccess/resolvePartnerAccessScope.js";
import { expandPromoPartners, getPromoPartnerOptions, PartnerExpansionTargetError, type PromoPartnerOption } from "../features/partnerAccess/promoPartnerExpansion.js";
import { setWorkspaceReportState } from "../features/partnerAccess/setWorkspaceReportState.js";
import { getWorkspacePartnerNames, getWorkspacePendingReports, getWorkspacePromoById, getWorkspacePromos } from "../features/partnerAccess/scopedWorkspaceReads.js";
import type { PartnerAccessScope } from "../features/partnerAccess/partnerAccess.types.js";
import { InvalidPartnerAssignmentError, listAdminPartnerCatalog, replaceUserPartnerAssignments, SuperuserAssignmentsError, type AdminPartnerCatalogItem, type AssignedPartner } from "../features/partnerAccess/partnerAssignments.js";
import { closeReportingPeriod, EmptyReportingPeriodError, getArchivedPeriod, getQuarterlySummary, listArchivedPeriods, listQuarterlySelections, ReportingPeriodNotReadyError, type ArchivedPeriod, type ArchivedPeriodDetail, type QuarterlySummary } from "../features/quarterlyReporting/quarterlyReporting.js";
import { ClosedReportingPeriodError } from "../features/quarterlyReporting/closedPeriods.js";
import { toPendingReportDto, toPromoDto, type PendingReportRecord, type PromoRecord } from "./dto.js";

type ReportRecord = Awaited<ReturnType<typeof setWorkspaceReportState>>;
export type ApiDependencies = { jwtSecret: string; findUserByEmail: (email: string) => Promise<User | null>; findUserById: (id: number) => Promise<User | null>; resolvePartnerAccessScope: (user: Pick<User, "id" | "role">) => Promise<PartnerAccessScope>; listUsers: () => Promise<ManagedUser[]>; createManagedUser: (email: string, password: string, role: UserRole, partnerKeys?: string[]) => Promise<ManagedUser>; updateManagedUser: (id: number, update: UserAdminUpdate) => Promise<ManagedUser | null>; updateManagedUserPassword: (id: number, password: string) => Promise<boolean>; deleteManagedKam: (id: number) => Promise<boolean>; listAdminPartnerCatalog: () => Promise<AdminPartnerCatalogItem[]>; replaceUserPartnerAssignments: (userId: number, partnerKeys: string[]) => Promise<AssignedPartner[] | null>; getPartnerNames: (scope: PartnerAccessScope) => Promise<string[]>; getAllPromos: (scope: PartnerAccessScope) => Promise<PromoRecord[]>; getPromoById: (id: string, scope: PartnerAccessScope) => Promise<PromoRecord | null>; getPromoPartnerOptions: (promoId: string, scope: PartnerAccessScope) => Promise<PromoPartnerOption[] | null>; expandPromoPartners: (promoId: string, partnerIds: string[], scope: PartnerAccessScope) => Promise<PromoRecord | null>; getPendingReports: (scope: PartnerAccessScope) => Promise<PendingReportRecord[]>; setReportState: (id: string, received: boolean, scope: PartnerAccessScope) => Promise<ReportRecord>; deletePromo: (id: string) => Promise<boolean>; removePromoPartner: (promoId: string, partnerId: string) => Promise<boolean>; listQuarterlySelections: (now?: Date) => Promise<{ quarters: Array<{ year: number; quarter: number }>; lobs: string[] }>; getQuarterlySummary: (year: number, quarter: number, lob: string) => Promise<QuarterlySummary>; closeReportingPeriod: (year: number, quarter: number, lob: string, userId: number, closedAt?: Date) => Promise<QuarterlySummary & { alreadyClosed: boolean }>; listArchivedPeriods: () => Promise<ArchivedPeriod[]>; getArchivedPeriod: (id: string) => Promise<ArchivedPeriodDetail | null>; now: () => Date };
const defaults: Omit<ApiDependencies, "jwtSecret"> = { findUserByEmail, findUserById, resolvePartnerAccessScope, listUsers, createManagedUser, updateManagedUser, updateManagedUserPassword, deleteManagedKam, listAdminPartnerCatalog, replaceUserPartnerAssignments, getPartnerNames: getWorkspacePartnerNames, getAllPromos: getWorkspacePromos, getPromoById: getWorkspacePromoById, getPromoPartnerOptions, expandPromoPartners, getPendingReports: getWorkspacePendingReports, setReportState: setWorkspaceReportState, deletePromo, removePromoPartner, listQuarterlySelections, getQuarterlySummary, closeReportingPeriod, listArchivedPeriods, getArchivedPeriod, now: () => new Date() };
const cookieOptions = { httpOnly: true, sameSite: "lax" as const, secure: process.env.NODE_ENV === "production", path: "/" };

export function createApi(overrides: Partial<ApiDependencies> = {}) {
  const services = { ...defaults, ...overrides };
  const jwtSecret = overrides.jwtSecret ?? process.env.AUTH_JWT_SECRET;
  if (!jwtSecret || jwtSecret.length < 32) throw new Error("AUTH_JWT_SECRET must contain at least 32 characters");
  const app = express();
  app.use(cors({ origin: "http://localhost:5173", credentials: true }));
  app.use(express.json());
  app.use(cookieParser());
  app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
  app.post("/api/auth/login", async (req, res, next) => { try { if (typeof req.body?.email !== "string" || typeof req.body?.password !== "string") { res.status(400).json({ error: "Email і password обов'язкові" }); return; } const user = await authenticateUser(req.body.email, req.body.password, services.findUserByEmail); if (!user) { res.status(401).json({ error: "Невірний email або пароль" }); return; } res.cookie(AUTH_COOKIE, signAuthToken(user, jwtSecret), { ...cookieOptions, maxAge: AUTH_SESSION_MAX_AGE_MS }); res.json(toSafeUser(user)); } catch (error) { next(error); } });
  app.post("/api/auth/logout", (_req, res) => { res.clearCookie(AUTH_COOKIE, cookieOptions); res.json({ success: true }); });
  const authenticated = requireAuth(jwtSecret, services.findUserById);
  const userAdminOnly: RequestHandler[] = [authenticated, requireCapability("manageUsers")];
  const assignmentAdminOnly: RequestHandler[] = [authenticated, requireCapability("managePartnerAssignments")];
  app.get("/api/auth/me", authenticated, (_req, res) => res.json(toSafeUser(res.locals.user)));
  const workspaceScope = (res: Response) => services.resolvePartnerAccessScope(res.locals.user);
  app.get("/api/partners", authenticated, async (_req, res, next) => { try { res.json(await services.getPartnerNames(await workspaceScope(res))); } catch (error) { next(error); } });
  app.get("/api/admin/partners", ...assignmentAdminOnly, async (_req, res, next) => { try { res.json(await services.listAdminPartnerCatalog()); } catch (error) { next(error); } });
  app.get("/api/users", ...userAdminOnly, async (_req, res, next) => { try { res.json(await services.listUsers()); } catch (error) { next(error); } });
  app.post("/api/users", ...userAdminOnly, async (req, res, next) => { try { const { email, password, role = "KAM", partnerKeys = [] } = req.body ?? {}; if (typeof email !== "string" || typeof password !== "string" || !["KAM", "PLM", "SUPERUSER"].includes(role) || !Array.isArray(partnerKeys) || partnerKeys.some((key) => typeof key !== "string")) { res.status(400).json({ error: "Email, password, коректна role і partnerKeys обов'язкові" }); return; } res.status(201).json(await services.createManagedUser(email, password, role, partnerKeys)); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") { res.status(409).json({ error: "Користувач із таким email уже існує" }); return; } if (error instanceof InvalidPartnerAssignmentError || error instanceof SuperuserAssignmentsError || (error instanceof Error && /Invalid email|at least 8 characters/.test(error.message))) { res.status(400).json({ error: error.message }); return; } next(error); } });
  app.patch("/api/users/:id", ...userAdminOnly, async (req, res, next) => { try { const id = Number(req.params.id); const { role, isActive } = req.body ?? {}; if (!Number.isInteger(id) || id <= 0 || (role === undefined && isActive === undefined) || (role !== undefined && !["KAM", "PLM", "SUPERUSER"].includes(role)) || (isActive !== undefined && typeof isActive !== "boolean")) { res.status(400).json({ error: "Некоректні дані користувача" }); return; } const updated = await services.updateManagedUser(id, { ...(role === undefined ? {} : { role }), ...(isActive === undefined ? {} : { isActive }) }); if (!updated) { res.status(404).json({ error: "Користувача не знайдено" }); return; } res.json(updated); } catch (error) { if (error instanceof LastActiveSuperuserError) { res.status(409).json({ error: "Має залишитися хоча б один активний SUPERUSER" }); return; } next(error); } });
  app.put("/api/users/:id/password", ...userAdminOnly, async (req, res, next) => { try { const id = Number(req.params.id); if (!Number.isInteger(id) || id <= 0 || typeof req.body?.password !== "string") { res.status(400).json({ error: "Коректний password обов'язковий" }); return; } if (!await services.updateManagedUserPassword(id, req.body.password)) { res.status(404).json({ error: "Користувача не знайдено" }); return; } res.json({ success: true }); } catch (error) { if (error instanceof Error && /at least 8 characters/.test(error.message)) { res.status(400).json({ error: error.message }); return; } next(error); } });
  app.delete("/api/users/:id", ...userAdminOnly, async (req, res, next) => { try { const id = Number(req.params.id); if (!Number.isInteger(id) || id <= 0) { res.status(400).json({ error: "Некоректний ID користувача" }); return; } if (!await services.deleteManagedKam(id)) { res.status(404).json({ error: "Користувача не знайдено" }); return; } res.json({ success: true }); } catch (error) { if (error instanceof SuperuserDeletionError) { res.status(409).json({ error: "SUPERUSER не можна видалити" }); return; } next(error); } });
  app.put("/api/users/:id/partners", ...assignmentAdminOnly, async (req, res, next) => { try { const id = Number(req.params.id); const { partnerKeys } = req.body ?? {}; if (!Number.isInteger(id) || id <= 0 || !Array.isArray(partnerKeys) || partnerKeys.some((key) => typeof key !== "string")) { res.status(400).json({ error: "Коректні partnerKeys обов'язкові" }); return; } const partners = await services.replaceUserPartnerAssignments(id, partnerKeys); if (!partners) { res.status(404).json({ error: "Користувача не знайдено" }); return; } res.json({ partners }); } catch (error) { if (error instanceof SuperuserAssignmentsError) { res.status(409).json({ error: error.message }); return; } if (error instanceof InvalidPartnerAssignmentError) { res.status(400).json({ error: error.message }); return; } next(error); } });
  app.get("/api/promos", authenticated, async (_req, res, next) => { try { res.json((await services.getAllPromos(await workspaceScope(res))).map((promo) => toPromoDto(promo, services.now()))); } catch (error) { next(error); } });
  app.get("/api/promos/:id/partner-options", authenticated, requireCapability("expandPromoPartners"), async (req, res, next) => { try { const options = await services.getPromoPartnerOptions(String(req.params.id), await workspaceScope(res)); if (!options) { res.status(404).json({ error: "Промо не знайдено" }); return; } res.json(options); } catch (error) { next(error); } });
  app.post("/api/promos/:id/partners", authenticated, requireCapability("expandPromoPartners"), async (req, res, next) => { try { const { partnerIds } = req.body ?? {}; if (!Array.isArray(partnerIds) || partnerIds.length === 0 || partnerIds.some((id) => typeof id !== "string" || !id)) { res.status(400).json({ error: "Оберіть хоча б одного партнера" }); return; } const promo = await services.expandPromoPartners(String(req.params.id), partnerIds, await workspaceScope(res)); if (!promo) { res.status(404).json({ error: "Промо не знайдено" }); return; } res.json(toPromoDto(promo, services.now())); } catch (error) { if (error instanceof PartnerExpansionTargetError) { res.status(403).json({ error: "Один або кілька партнерів недоступні" }); return; } next(error); } });
  app.get("/api/promos/:id", authenticated, async (req, res, next) => { try { const promo = await services.getPromoById(String(req.params.id), await workspaceScope(res)); if (!promo) { res.status(404).json({ error: "Промо не знайдено" }); return; } res.json(toPromoDto(promo, services.now())); } catch (error) { next(error); } });
  app.get("/api/reports/pending", authenticated, async (_req, res, next) => { try { res.json((await services.getPendingReports(await workspaceScope(res))).map(toPendingReportDto)); } catch (error) { next(error); } });
  app.patch("/api/promo-partners/:id/report", authenticated, requireCapability("mutateReportState"), async (req, res, next) => { try { const id = String(req.params.id); if (typeof req.body?.received !== "boolean") { res.status(400).json({ error: "Поле received має бути boolean" }); return; } const updated = await services.setReportState(id, req.body.received, await workspaceScope(res)); if (!updated) { res.status(404).json({ error: "Участь партнера не знайдено" }); return; } res.json({ promoPartnerId: updated.id, reportReceived: updated.reportReceived, reportReceivedAt: updated.reportReceivedAt?.toISOString() ?? null }); } catch (error) { next(error); } });
  app.delete("/api/promos/:promoId", authenticated, requireCapability("deletePromo"), async (req, res, next) => { try { if (!await services.deletePromo(String(req.params.promoId))) { res.status(404).json({ error: "Промо не знайдено" }); return; } res.json({ success: true }); } catch (error) { next(error); } });
  app.delete("/api/promos/:promoId/partners/:partnerId", authenticated, requireCapability("deletePromoPartner"), async (req, res, next) => { try { if (!await services.removePromoPartner(String(req.params.promoId), String(req.params.partnerId))) { res.status(404).json({ error: "Участь партнера не знайдено" }); return; } res.json({ success: true }); } catch (error) { next(error); } });

  const reportingParams = (source: Record<string, unknown>) => { const year = Number(source.year); const quarter = Number(source.quarter); const lob = typeof source.lob === "string" ? source.lob.trim() : ""; return Number.isInteger(year) && year >= 2000 && year <= 2100 && [1, 2, 3, 4].includes(quarter) && lob ? { year, quarter, lob } : null; };
  app.get("/api/reporting/selections", authenticated, requireCapability("viewQuarterlyReporting"), async (_req, res, next) => { try { res.json(await services.listQuarterlySelections(services.now())); } catch (error) { next(error); } });
  app.get("/api/reporting/summary", authenticated, requireCapability("viewQuarterlyReporting"), async (req, res, next) => { try { const params = reportingParams(req.query); if (!params) { res.status(400).json({ error: "Оберіть коректний квартал і LOB" }); return; } res.json(await services.getQuarterlySummary(params.year, params.quarter, params.lob)); } catch (error) { next(error); } });
  app.post("/api/reporting/close", authenticated, requireCapability("closeReportingPeriod"), async (req, res, next) => { try { const params = reportingParams(req.body ?? {}); if (!params) { res.status(400).json({ error: "Оберіть коректний квартал і LOB" }); return; } res.json(await services.closeReportingPeriod(params.year, params.quarter, params.lob, res.locals.user.id, services.now())); } catch (error) { if (error instanceof EmptyReportingPeriodError) { res.status(409).json({ error: "Немає звітів для закриття" }); return; } if (error instanceof ReportingPeriodNotReadyError) { res.status(409).json({ error: "Не всі звіти отримано" }); return; } next(error); } });
  app.get("/api/reporting/archive", authenticated, requireCapability("viewArchive"), async (_req, res, next) => { try { res.json(await services.listArchivedPeriods()); } catch (error) { next(error); } });
  app.get("/api/reporting/archive/:id", authenticated, requireCapability("viewArchive"), async (req, res, next) => { try { const period = await services.getArchivedPeriod(String(req.params.id)); if (!period) { res.status(404).json({ error: "Архівний період не знайдено" }); return; } res.json(period); } catch (error) { next(error); } });

  if (process.env.NODE_ENV === "production") {
    const uiDistPath = path.resolve(process.cwd(), "ui/dist");
    const serveUi = express.static(uiDistPath);
    app.use((req, res, next) => {
      if (/^\/api(?:\/|$)/i.test(req.path)) return next();
      if (req.method !== "GET" && req.method !== "HEAD") return next();
      serveUi(req, res, (error) => {
        if (error) return next(error);
        res.sendFile(path.join(uiDistPath, "index.html"), (error) => {
          if (error) next(error);
        });
      });
    });
  }

  app.use((_req: Request, res: Response) => res.status(404).json({ error: "Маршрут не знайдено" }));
  app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { if (error instanceof ClosedReportingPeriodError) { res.status(409).json({ error: "Звітний період закрито. Історичні дані доступні лише для перегляду." }); return; } console.error("API request failed", error); res.status(500).json({ error: "Внутрішня помилка сервера" }); });
  return app;
}
