import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { ArchiveDetail } from "./ArchivePage";
import { QuarterlySummaryView } from "./QuarterlyReporting";
import type { ArchivedPeriodDetail, QuarterlySummary } from "../types";

const summary = (overrides: Partial<QuarterlySummary> = {}): QuarterlySummary => ({ year: 2026, quarter: 3, lob: "iPhone", status: "OPEN", ready: false, closedAt: null, closedBy: null, promoCount: 3, expectedReports: 40, receivedReports: 37, pendingReports: 3, completionPercentage: 92.5, partners: [{ partnerId: "rozetka", partnerName: "Rozetka", expectedReports: 13, receivedReports: 11, pendingReports: 2, pending: [{ promoPartnerId: "pp-1", promoId: "p-1", promoName: "Promo A", startDate: "2026-09-01T00:00:00.000Z", endDate: "2026-09-14T00:00:00.000Z", partnerId: "rozetka", partnerName: "Rozetka" }] }], pending: [], ...overrides });

describe("quarterly reporting presentation", () => {
  it("renders received/expected, percentage, partner progress and missing report details", () => { const html = renderToStaticMarkup(<QuarterlySummaryView summary={summary()} canClose onClose={vi.fn()} />); expect(html).toContain("37 / 40 отримано"); expect(html).toContain("92.5%"); expect(html).toContain("Rozetka"); expect(html).toContain("11 / 13"); expect(html).toContain("Promo A"); expect(html).toContain("disabled"); });
  it("does not consider 0/0 ready", () => { const html = renderToStaticMarkup(<QuarterlySummaryView summary={summary({ expectedReports: 0, receivedReports: 0, pendingReports: 0, completionPercentage: 0, partners: [] })} canClose onClose={vi.fn()} />); expect(html).toContain("0 / 0 отримано"); expect(html).toContain("немає очікуваних звітів"); expect(html).toContain("disabled"); });
  it("enables closure only for PLM-ready data and hides it from read-only roles", () => { expect(renderToStaticMarkup(<QuarterlySummaryView summary={summary({ ready: true, receivedReports: 40, pendingReports: 0 })} canClose onClose={vi.fn()} />)).not.toContain("disabled"); expect(renderToStaticMarkup(<QuarterlySummaryView summary={summary({ ready: true })} canClose={false} onClose={vi.fn()} />)).not.toContain("Закрити квартал"); });
  it("renders archive detail without mutation controls", () => { const period: ArchivedPeriodDetail = { ...summary({ status: "CLOSED", ready: false, receivedReports: 40, pendingReports: 0, closedAt: "2026-10-15T00:00:00.000Z" }), id: "period-1", promos: [{ id: "p-1", lob: "iPhone", name: "Promo A", startDate: "2026-09-01T00:00:00.000Z", endDate: "2026-09-14T00:00:00.000Z", partners: [{ promoPartnerId: "pp-1", partnerId: "rozetka", partnerName: "Rozetka", reportReceived: true, reportReceivedAt: "2026-10-01T00:00:00.000Z", rawEmailSubject: null }] }] }; const html = renderToStaticMarkup(<ArchiveDetail period={period} />); expect(html).toContain("Дані доступні лише для перегляду"); expect(html).not.toContain("Додати партнерів"); expect(html).not.toContain("Видалити"); expect(html).not.toContain("type=\"checkbox\""); });
});
